const csvPath='./btc-price-2025-ahr999.csv'
const startDateUtc=new Date(Date.UTC(2024,10,1))
const endDateUtc=new Date(Date.UTC(2025,10,15))
let priceRows=[]
let ahrMap=new Map()
let chart
let gPriceMap=new Map()
function fmtUsd(n){return '$'+n.toLocaleString('en-US',{maximumFractionDigits:2})}
function fmtBtc(n){return n.toFixed(8)}
function toKey(d){return d.toISOString().slice(0,10)}
function parseDateStr(s){const parts=s.split('/');const y=parseInt(parts[0],10);const m=parseInt(parts[1],10)-1;const d=parseInt(parts[2],10);return new Date(Date.UTC(y,m,d))}
async function loadCsv(){const res=await fetch(csvPath+'?v='+Date.now());const txt=await res.text();const lines=txt.trim().split(/\r?\n/);const rows=[];for(let i=1;i<lines.length;i++){const [ds,ps]=lines[i].split(',');const date=parseDateStr(ds.trim());const price=parseFloat(ps.trim());rows.push({date,price})}rows.sort((a,b)=>a.date-b.date);return rows}
function filterRange(rows,s,e){return rows.filter(r=>r.date>=s&&r.date<=e)}
function buildPriceMap(rows){const m=new Map();for(const r of rows){m.set(toKey(r.date),r.price)}return m}
function rollingDcaCost(rows){const invs=rows.map(r=>1/r.price);let sum=0;const costs=new Map();for(let i=0;i<rows.length;i++){sum+=invs[i];if(i>=200){sum-=invs[i-200]}if(i>=199){const cost=200/sum;costs.set(toKey(rows[i].date),cost)} }return costs}
function indexGrowthValuation(ageDays){const v=Math.pow(10,5.84*Math.log10(ageDays)-17.01);return v}
function daysSinceGenesis(d){const genesis=new Date(Date.UTC(2009,0,3));const ms=24*3600*1000;return Math.floor((d-genesis)/ms)+1}
function computeAhr(rows){const dca=rollingDcaCost(rows);const m=new Map();for(const r of rows){const k=toKey(r.date);if(!dca.has(k))continue;const age=daysSinceGenesis(r.date);const iv=indexGrowthValuation(age);const a=(r.price/dca.get(k))*(r.price/iv);m.set(k,a)}return m}
function lastDayOfMonth(y,m){return new Date(Date.UTC(y,m+1,0))}
function getMonthlyDates(s,e,dom,priceMap){const dates=[];let y=s.getUTCFullYear();let m=s.getUTCMonth();while(y<e.getUTCFullYear()||(y===e.getUTCFullYear()&&m<=e.getUTCMonth())){const ld=lastDayOfMonth(y,m);let d=Math.min(dom,ld.getUTCDate());let dt=new Date(Date.UTC(y,m,d));if(dt<s)dt=s;if(dt>ld)dt=ld;const k=toKey(dt);if(priceMap.has(k)&&dt>=s&&dt<=e)dates.push(dt);m++;if(m>11){m=0;y++}}return dates}
function getAhrDates(rowsInRange,threshold){const dates=[];for(const r of rowsInRange){const k=toKey(r.date);const a=ahrMap.get(k);if(a!==undefined&&a<=threshold)dates.push(r.date)}return dates}
function getAhrMonthlyDates(rowsInRange,s,e,threshold,priceMap){const dates=[];let y=s.getUTCFullYear();let m=s.getUTCMonth();while(y<e.getUTCFullYear()||(y===e.getUTCFullYear()&&m<=e.getUTCMonth())){const monthStart=new Date(Date.UTC(y,m,1));const ms=monthStart<s?s:monthStart;const monthEnd=lastDayOfMonth(y,m);const me=monthEnd>e?e:monthEnd;let picked=null;for(const r of rowsInRange){if(r.date>=ms&&r.date<=me){const a=ahrMap.get(toKey(r.date));if(a!==undefined&&a<=threshold){picked=r.date;break}}}if(!picked){const k=toKey(me);if(priceMap.has(k))picked=me}if(picked)dates.push(picked);m++;if(m>11){m=0;y++}}return dates}
function computeSeries(rowsInRange,priceMap,dates,amount){const dateSet=new Set(dates.map(toKey));const labels=[];const invested=[];const value=[];let totalInvested=0;let btc=0;const buyMarkers=[];for(const r of rowsInRange){const k=toKey(r.date);labels.push(k);if(dateSet.has(k)){const p=priceMap.get(k);const addBtc=amount/p;btc+=addBtc;totalInvested+=amount;buyMarkers.push({x:k,y:btc*p})}
value.push(btc*priceMap.get(k));invested.push(totalInvested)}return{labels,invested,value,totalInvested,btc,buyCount:dates.length,buyMarkers}}
function renderChart(labels,invested,value,buyMarkers){const ctx=document.getElementById('chart').getContext('2d');if(chart)chart.destroy();const cfg={type:'line',data:{labels:labels,datasets:[{label:'期末资产价值',data:value,borderColor:'#FF9900',backgroundColor:'rgba(255,153,0,0.15)',borderWidth:2,pointRadius:0,tension:0.25},{label:'累计投入',data:invested,borderColor:'#1A1A1A',backgroundColor:'rgba(26,26,26,0.1)',borderWidth:2,pointRadius:0,tension:0.25},{type:'scatter',label:'买入标记',data:buyMarkers,borderColor:'#FF9900',backgroundColor:'#FF9900',pointRadius:3,hoverRadius:6}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{tooltip:{callbacks:{footer:function(items){if(!items||!items.length)return '';const k=items[0].label;const p=gPriceMap.get(k);const a=ahrMap.get(k);const priceStr=p?('$'+Number(p).toLocaleString('en-US')):'-';const aStr=(a!==undefined)?a.toFixed(4):'-';return ['价格 '+priceStr,'AHR999 '+aStr]}}}}}};chart=new Chart(ctx,cfg)}
function updateMetrics(totalInvested,finalValue,btc,buyCount){const profit=finalValue-totalInvested;const roi=totalInvested>0?profit/totalInvested:0;document.getElementById('m-invested').textContent=fmtUsd(totalInvested);document.getElementById('m-value').textContent=fmtUsd(finalValue);document.getElementById('m-profit').textContent=fmtUsd(profit)+'  ('+(roi*100).toFixed(2)+'%)';document.getElementById('m-btc').textContent=fmtBtc(btc);document.getElementById('m-count').textContent=String(buyCount)}
function getMode(){const active=document.querySelector('.tab.active');return active.getAttribute('data-mode')}
function setActiveTab(mode){document.querySelectorAll('.tab').forEach(b=>{b.classList.toggle('active',b.getAttribute('data-mode')===mode)});document.getElementById('monthly-controls').classList.toggle('hidden',mode!=='monthly');document.getElementById('ahr-controls').classList.toggle('hidden',mode!=='ahr')}
async function init(){priceRows=await loadCsv();ahrMap=computeAhr(priceRows);const filtered=filterRange(priceRows,startDateUtc,endDateUtc);gPriceMap=buildPriceMap(priceRows);const amountInput=document.getElementById('amount');const domRange=document.getElementById('dom');const domValue=document.getElementById('dom-value');const thresholdSel=document.getElementById('ahr-threshold');const tabs=document.querySelectorAll('.tab');tabs.forEach(t=>t.addEventListener('click',()=>{setActiveTab(t.getAttribute('data-mode'))}));domRange.addEventListener('input',()=>{domValue.textContent=domRange.value});document.getElementById('run').addEventListener('click',()=>{const mode=getMode();const amount=Math.max(1,Number(amountInput.value||100));let dates=[];if(mode==='monthly'){dates=getMonthlyDates(startDateUtc,endDateUtc,Number(domRange.value),gPriceMap)}else{const freq=document.getElementById('ahr-frequency').value;if(freq==='monthly'){dates=getAhrMonthlyDates(filtered,startDateUtc,endDateUtc,Number(thresholdSel.value),gPriceMap)}else{dates=getAhrDates(filtered,Number(thresholdSel.value))}}const series=computeSeries(filtered,gPriceMap,dates,amount);renderChart(series.labels,series.invested,series.value,series.prices,series.buyMarkers);const lastKey=toKey(endDateUtc);const finalPrice=gPriceMap.get(lastKey);const side=document.getElementById('price-side');if(side)side.textContent=fmtUsd(finalPrice);updateMetrics(series.totalInvested,series.btc*finalPrice,series.btc,series.buyCount)});document.getElementById('run').click()}
window.addEventListener('DOMContentLoaded',init)